---
title: "Untitled"
output: html_document
---

```{r}
install.packages("gravity")
```

```{r}
options(max.print=1000000)
options(scipen=999)

library(tidyverse)
library(gravity)
```

```{r}
data = read.csv('interactions.csv')
```

```{r}
loglm = lm(log(mig_total+0.5)~log(pop_total_i)+log(pop_total_j)+log(dist), data=data) 
loglm %>% summary() #+0.5

loglm2 = lm(log(mig_total+1)~log(pop_total_i)+log(pop_total_j)+log(dist), data=data) 
loglm2 %>% summary() #+1

nozero = lm(log(mig_total)~log(pop_total_i)+log(pop_total_j)+log(dist), data=filter(data, mig_total != 0))

poissson = glm(mig_total~log(pop_total_i)+log(pop_total_j)+log(dist), data=data, family="poisson")
poissson %>% summary() #poisson
#glm(mig_total~pop_total_i+pop_total_j+dist, data=data, family="poisson") %>% summary() #poisson
#log(data$mig_total)


hist(data$mig_total[data$mig_total<100], breaks = 200)
hist(log(data$mig_total+0.5), breaks = 100)
mean(data$mig_total, na.rm = TRUE)
var(data$mig_total, na.rm = TRUE)

quasipoisson = glm(mig_total~log(pop_total_i)+log(pop_total_j)+log(dist), data=data, family="quasipoisson") 
quasipoisson %>% summary() #quasipoisson

plot(y = data$mig_total, x = data$distance_capitals)
plot(y = log(data$mig_total), x = log(data$distance_capitals))
plot(y = log(data$mig_total), x = log(data$pop_total_i))
plot(y = log(data$mig_total), x = log(data$pop_total_j))

ggplot(data = data) + geom_point(aes(y=mig_total, x=distance_capitals))

ggplot(data = data) + geom_point(aes(y=mig_total, x=pop_total_j))

#sum1 = data %>% group_by(from_i) %>% summarize(outmigration = sum(mig_total))
#sum2 = data %>% group_by(to_j) %>% summarize(inmigration = sum(mig_total))
#sum = left_join(sum1, sum2, by = c("from_i" = "to_j")) %>% left_join(pop, by = c("from_i" = "index"))

#sum$pop = sum$pop_f+sum$pop_m

ggplot(sum) + geom_point(aes(y = outmigration, x = pop, color = "red")) + geom_point(aes(y = inmigration, x = pop, color = "blue"))

pseudeml = ppml(
    dependent_variable = "mig_total",
    distance = "dist",
    additional_regressors = c("log_pop_i", "log_pop_j"),
    data = data
  )
pseudeml %>% summary()

export_summs(loglm, poissson, quasipoisson)
export_summs(pseudeml)

poissson %>% plot()
loglm %>% plot()

ggplot() + 
  geom_point(aes(y = as.numeric(predict(loglm)), x = unlist(loglm$model[1]))) + geom_abline()

ggplot() + 
  geom_point(aes(y = as.numeric(loglm$residuals), x = unlist(loglm$model[1]))) + geom_hline(yintercept = 0)


fixed_effects("mig_total", "dist", NULL, "name_i", "name_j", data = data) %>% summary() #fe
fixed_effects("mig_total", "dist", c("log_pop_i", "log_pop_j"), "name_i", "name_j", data = data) %>% summary() #fe
lm(log(mig_total)-log_pop_i-log_pop_j~dist+name_i+name_j, data=filter(data, mig_total != 0)) %>% summary
lm(log(mig_total)~log_pop_i+log_pop_j+dist+name_i+name_j, data=filter(data, mig_total != 0)) %>% summary

ols("mig_total", "dist", additional_regressors = NULL, "pop_total_i", "pop_total_j", "name_i", "name_j", data = data) %>% summary()
#lm(log(mig_total)~log(pop_total_i)+log(pop_total_j)+log(dist), data=filter(data, mig_total != 0)) %>% summary()

glm(log(mig_total+0.5)~log(pop_total_i)+log(pop_total_j)+log(dist), data=data, family="gaussian") %>% summary()

tobit(dependent_variable="mig_total", distance="dist", c("log_pop_i", "log_pop_j"), data = data) %>% summary()
ek_tobit(dependent_variable="mig_total", distance="dist", c("log_pop_i", "log_pop_j"), code_destination="to_j",vcerobust=TRUE, data = data) %>% summary()

loglm2$residuals %>% hist()
pseudeml$residuals %>% hist()

stargazer(loglm, loglm2, poissson, type="html")

export_summs(nozero, loglm, loglm2, quasipoisson, to.file="docx", file.name="table.docx")

filter(data, mig_total==0) %>% view()
```


```{r}
loglm = lm(log(mig_total+1)~log(pop_total_i)+log(pop_total_j)+log(distance_capitals), data=data) 
loglm %>% summary()

poissson = glm(mig_total~log(pop_total_i)+log(pop_total_j)+log(distance_capitals), data=data, family="poisson")
poissson %>% summary() #poisson

quasipoisson = glm(mig_total~log(pop_total_i)+log(pop_total_j)+log(distance_capitals), data=data, family="quasipoisson") 
quasipoisson %>% summary() #quasipoisson
```


```{r}
data$log_pop_i = log(data$pop_total_i)
data$log_pop_j = log(data$pop_total_j)

pseudeml = ppml(
    dependent_variable = "mig_total",
    distance = "distance_capitals",
    additional_regressors = c("log_pop_i", "log_pop_j"),
    data = data
  )
pseudeml %>% summary()
```
```{r}
glm(mig_total~log(pop_total_i)+log(pop_total_j)+log(distance_capitals)+
      log(abs(lit_rate_total_j - lit_rate_total_i))+
      log(abs(pop_rate_j - pop_rate_i))+
      log(abs(industry_pc_i - industry_pc_j)), 
    data=data, family="quasipoisson") %>% summary()
```


```{r}
glm(mig_total~log(pop_total_i)+log(pop_total_j)+log(distance_capitals)+(macroregion_i:macroregion_j)+
      log(lit_rate_total_j - lit_rate_total_i)+
      log(pop_rate_j - pop_rate_i)+
      log(industry_pc_i - industry_pc_j), 
    data=data, family="quasipoisson") %>% summary()
```

```{r}
glm(mig_total~log(pop_total_i)+log(pop_total_j)+log(distance_capitals)+
      log(lit_rate_total_j) + log(lit_rate_total_i)+
      log(pop_rate_j) + log(pop_rate_i)+
      log(industry_pc_i) + log(industry_pc_j),
    data=subset(data, macroregion_i!='Poland' & macroregion_j!='Poland'), family="quasipoisson") %>% summary()
```


```{r}
glm(mig_total~log(pop_total_i)+log(pop_total_j)+log(distance_capitals)+
      log(lit_rate_total_j) + log(lit_rate_total_i)+
      log(pop_rate_j) + log(pop_rate_i)+
      log(industry_pc_j) + log(industry_pc_i),
    data=data, family="quasipoisson") %>% summary()
```




